# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_core', models.IntegerField()),
                ('numOfDocuments', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRepresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representation', models.TextField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cluster')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('url', models.TextField()),
                ('content', models.TextField()),
                ('time', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
